### ISSUE TITLE
msdf-gdx

### ISSUE THREAD

**Issue by mgood7123** [tommyettinger/textratypist#10]
is this compatible with https://github.com/maltaisn/msdf-gdx ?

**Comment by tommyettinger** [comment]
It will be in the next stable release, or sooner if you use a JitPack commit like https://jitpack.io/#tommyettinger/textratypist/34ddccf045 .

Currently, it looks like this with one of the mtsdf fonts produced by https://github.com/maltaisn/msdf-gdx-gen :
![Preview](https://i.imgur.com/N1Kc9pW.png)

The nice thing about msdf-gdx-gen is that it has kerning when the font has that info. The bad thing about it is that apparently, it doesn't ever output a space character (` `) in the .fnt, and I'm not sure why.

I'm leaving this open in case other features from msdf-gdx are requested.

**Comment by tommyettinger** [comment]
So, good news! The latest version of TextraTypist supports fonts generated with msdf-gdx-gen, and as long as they're made at a somewhat-large size, the baseline should be bug-free (this was a problem with earlier versions of msdf-gdx, maybe because the fonts I made were too small). The alpha channel is not currently used, since as far as I could tell it was only used for drop shadow and changes in weight, but drop shadow is supported in other ways here, and weight changes seem challenging to work with. Also, the latest version of msdf-gdx-gen produces the space character, hooray! I'm closing this now.
