### ISSUE TITLE
TextraLabel with wrap returns wrong height.

### ISSUE THREAD

**Issue by Trurl101** [tommyettinger/textratypist#19]
If I set wrapping for a Textralabel it wraps the text correctly but returns wrong height of the Actor. "getHeight" or "getPrefHeight" always return just the line height of the unwrapped text.

After some experimenting I discovered if I set the attributes in a specific order it works correct:
1. set wrapping
2. set size
3. set text

```
TextraLabel label = new TextraLabel(text, style);
label.setWrap(true);
label.setSize(500, 100);
label.setText(text);
```

If I use this order label.getPrefheight returns the correct height. With the normal scene2D Label setWrap and setSize works in every order and without the need to set the text again.

I think the bug results of this:
 - in "setSize" the "setTargetWidth" is only triggered if wrap is already true. I think it must be set every time or set in "setWrap" too.
 - "setText" triggers somehow to set the correct values in layout. I don't know if this happens in "font.markup" or somehow trough "invalidateHierarchy". But that must be done in "setSize" and "setWrap" too.

**Comment by tommyettinger** [comment]
I don't think this is a bug. The regular scene2d.ui Label class also misreports height if layout() (or pack(), which calls layout()) hasn't yet been called on whatever contains that Label. When layout() is called, it sets the actual width and height of actors, respecting wrapping and preferred sizes. The last line of TextraLabel.setText() is `invalidateHierarchy();` , and that makes the next attempt to draw the TextraLabel request layout() to be called. Label also invalidates hierarchy in setText() and setStyle(); it calls setStyle() in its constructor. I've tried adding
```java
        invalidateHierarchy();
        setSize(layout.getWidth(), layout.getHeight());
```

to TextraLabel's constructor (the same as Label), and all it does is make the height pre-layout() change to one line's height rather than the wrapped height, which matches Label behavior. Without that, it uses 0 as the height before layout() is called.

The sizing logic in scene2d.ui is an absolute labyrinth, missing only a minotaur. I'd rather not mess with sizing more than I have to.

**Comment by tommyettinger** [comment]
Calling layout() directly on a TextraLabel (or Label) wouldn't solve anything, since it needs to be called on what contains the TextraLabel (or Label). None of your examples do this... Even if you aren't using scene2d.ui's Table for setting up placements, you can put a TextraLabel in a scene2d.ui Container<TextraLabel>, and configure the Container's size like you would a Table cell. Wrapping only makes sense if there are some bounds to force wrapping on an edge. TextraLabel.layout has a target width, which can be used to do this, but I think a better solution is a Table cell or Container setting the width.

**Comment by Trurl101** [comment]
> Calling layout() directly on a TextraLabel (or Label) wouldn't solve anything, since it needs to be called on what contains the TextraLabel (or Label). None of your examples do this... Even if you aren't using scene2d.ui's Table for setting up placements, you can put a TextraLabel in a scene2d.ui Container, and configure the Container's size like you would a Table cell. Wrapping only makes sense if there are some bounds to force wrapping on an edge. TextraLabel.layout has a target width, which can be used to do this, but I think a better solution is a Table cell or Container setting the width.

I don't understand this. Perhaps we are talking about difference things. I use this approach and it gives me the expected results, always the correct value for getPrefHeight, and that is what this was about for me.

**Comment by raeleus** [comment]
I see what is at issue here and @Trurl101 has a point. This is normally not an issue for users putting the label in a Scene2D layout. It's only a problem if a user wants to get the height ahead of time before it is drawn. The workaround is to simply call textraLabel.validate() before you get the height (no need to set the text in a separate line).
I agree with the sentiment that messing around with the size code is a perilous task, but I think the solution Trurl101 has provided with prefSizeInvalid is adequate. I would only instead use validate() instead of layout() for efficiency. It seems to work in my tests, but it needs to be tested more thoroughly just to be safe. Thanks folks!

**Comment by tommyettinger** [comment]
OK, I'll go with the first suggestion I think, substituting validate() for layout().
