### ISSUE TITLE
BUG: Line wrapping with `Align.center` is wrong for `TextraLabel`

### ISSUE THREAD

**Issue by Daniikk1012** [tommyettinger/textratypist#6]
This is how it looks like:

![изображение](https://user-images.githubusercontent.com/49123959/185638610-066051e6-924e-4e72-9a2a-f714581bf14c.png)

This is how it is supposed to look like (In this image `TypingLabel` is used, seems like the issue does not exist for it):

![изображение](https://user-images.githubusercontent.com/49123959/185639147-2510e9ab-996a-46ab-aa7b-a19fc5d5f63a.png)

**Comment by tommyettinger** [comment]
This is an interesting one... The wrap width also seems smaller for that TypingLabel. This is using the latest release, 0.7.1 ? I'll try to verify over here and track down what might be causing this.

**Comment by tommyettinger** [comment]
There's now a test that tries to replicate this, though I don't know all of the code involved with the buggy original screenshot. The test looks like this with TextraLabel, and the same with TypingLabel: ![Centered...](https://i.imgur.com/LZPC70o.png) It's quite likely that there's some corner-case bug somewhere in the library, because that type of bug seems to pop up like a weed... Maybe you encountered the bug in a scene2d.ui Cell that contained a TextraLabel, rather than a TextraLabel on its own like in Issue6Test?

**Comment by tommyettinger** [comment]
This might be fixed by the latest commit: 

![Fixed?](https://i.imgur.com/ERK3xsY.png)

You can try it yourself using a JitPack dependency; I'd really like to know if this fixes the bug in your case. https://jitpack.io/#tommyettinger/textratypist/7168f0590c

A potential issue here is that TypingLabel seems to wrap more frequently (with less space permitted for the words) than TextraLabel. I'm not sure what's happening other than a possible difference between the two methods that can do word wrapping.

**Comment by Daniikk1012** [comment]
Thanks, I'll try it and tell you if it fixes the issue.

About wrapping more frequently - it is probably due to the fact that the width of my `TypingLabel` is just smaller than yours, so it is no surprise.

**Comment by Daniikk1012** [comment]
Seems to be working, closing the issue
