### ISSUE TITLE
Why set glyph just to char

### ISSUE THREAD

**Issue by tlz4320** [tommyettinger/textratypist#7]
In font, it can be int when add to mapping, but finally only consider it as char with 0xFFFF.
Therefore, if I want to add some image I like, I have to set value lower than 0xFFFF, which is limited.
Why not let glyph value could be long when searching in mapping.

**Comment by tommyettinger** [comment]
The main reason is simply that `String`s in Java are only reasonably usable as sequences of `char`; they even implement `CharSequence`. The code in Java to deal with "astral plane" codepoints, that is, those above `\uFFFF` or 65535, is very clumsy and does not work well with sequential iteration -- sometimes you read one `char` normally, but sometimes you encounter part of a "surrogate pair" and you need to read two `char`s. Some code here uses RegExodus to search for specific patterns in Strings, and that code is not prepared for greater-than-16-bit chars. In general, code that has to use many short `String`s to represent more than 16 bits in a character, isn't going to be friendly for allocation. We're already having trouble with TypingLabel allocations on platforms like Android, and at some point I will try to track down what causes that, but I don't want to pile on more allocations for, let's face it, a niche feature. Every emoji in the latest Twemoji release fits comfortably in the private use area (PUA) of Unicode, 3619 of them. There are 6400 codepoints in the PUA, leaving 2781 chars for whatever you need, even if you have all of Twemoji in there, with a guarantee that you won't overlap with an already-assigned character. I have a whole (large) game's worth of assets that fit in under 3000 images, including between 4 and 8 animation frames for almost everything. I don't really know what use cases would require more than 65536 chars, other than maybe handling obscure Chinese characters or Japanese kanji.

The other technical reason is that we've almost run out of bits in each `long` to store a glyph, since it currently uses 16 bits for a `char`, 32 bits for the color (which could be reduced to 31, but it would be tricky), 1 bit for bold, 1 oblique, 1 underline, 1 strikethrough, 2 for script modes like superscript, 4 for font selection, and 4 for scale. This leaves 2 sequential bits and one other bit as unused, with one of the sequential bits the aforementioned 32nd bit of color. Even this is a challenge to change, because kerning is currently represented using ints (each 32 bits) to represent ordered pairs of 16-bit chars, and going to ints for glyphs would need a LongIntMap instead of a LongLongMap. That isn't a huge problem in itself; I have the code for such a map already written in [jdkgdxds](https://github.com/tommyettinger/jdkgdxds), but it requires yet more rewriting for, again, a niche feature.

Lastly, the reason I use IntIntMap currently (and other int-based maps for chars) is just because that's what libGDX offers; there is no CharCharMap or anything in libGDX, and I would need to implement my own.

I'm closing this because it would be an incredibly large amount of work, would probably worsen performance, and it doesn't seem worth it.

**Comment by tlz4320** [comment]
Thank you for replying. And thank you for your great work. In fact, I tried to change it yesterday and I found that is really a large work. Now I just choose what you said, by re-using remained region to put my own images in font.
